name: google_drive_realtime
version: 0.0.8
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: With that package you will be able to use Google Drive Realtime API from Dart scripts.
homepage: https://github.com/a14n/dart-google-drive-realtime
dependencies:
  js: '>=0.0.22 <1.0.0'
  meta: any
dev_dependencies:
  browser: any
  unittest: any
