name: google_drive_realtime
version: 0.0.9-dev
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: A package to use Google Drive Realtime API from Dart scripts.
homepage: https://github.com/a14n/dart-google-drive-realtime
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  js_wrapping: '>=0.1.1 <0.2.0'
dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  editor_build: '>=0.0.4 <0.1.0'
  js_wrapping_generator: '0.0.3'
  path: '>=0.9.0 <0.10.0'
  unittest: '>=0.9.0 <0.10.0'
