name: google_drive_realtime
version: 0.0.4-dev
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: With that package you will be able to use Google Drive Realtime API from Dart scripts.
homepage: https://github.com/a14n/dart-google-drive-realtime
dev_dependencies:
  unittest: any
  browser: any
dependencies:
  meta: any
  js: '>=0.0.22 <1.0.0'
