name: google_drive_realtime
version: 0.0.9-dev
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: A package to use Google Drive Realtime API from Dart scripts.
homepage: https://github.com/a14n/dart-google-drive-realtime
dependencies:
  js_wrapping:
    path: ../dart-js-wrapping
    #git:
    #  url: https://github.com/a14n/dart-js-wrapping.git
    #  ref: dart-js
  meta: any
dev_dependencies:
  browser: any
  editor_build: any
  path: any
  unittest: any
